databases:
  - name: Hello
    databaseName: hello_5a12
    user: hello_5a12_user

services:
  - type: web
    name: Jhonella App 
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Hello
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false